# Generated by Django 5.0 on 2024-01-17 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('desc', models.TextField(default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='place/image')),
            ],
        ),
    ]
